- src/main/java/com/kkosoonnae/customer/controller/CustomerController.java
- src/main/java/com/kkosoonnae/customer/dto/InfoDto.java
- src/main/java/com/kkosoonnae/customer/service/CustomerService.java
- src/main/java/com/kkosoonnae/jpa/entity/CustomerDtl.java
> [feature] customer : 회원 정보 수정 API 개발

- src/main/java/com/kkosoonnae/jpa/entity/Review.java
- src/main/java/com/kkosoonnae/jpa/entity/StoreImg.java
- src/main/java/com/kkosoonnae/jpa/projection/StoreDetailViewProjection.java
- src/main/java/com/kkosoonnae/jpa/projection/StoreListViewProjection.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreImgRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StyleRepository.java
- src/main/java/com/kkosoonnae/store/controller/StoreController.java
- src/main/java/com/kkosoonnae/store/dto/StoreDetailViewResponseDto.java
- src/main/java/com/kkosoonnae/store/dto/StoreDetailWithImageResponseDto.java
- src/main/java/com/kkosoonnae/store/dto/StoreDto.java
- src/main/java/com/kkosoonnae/store/dto/StoreImgDto.java
- src/main/java/com/kkosoonnae/store/dto/StoreListViewResponseDto.java
- src/main/java/com/kkosoonnae/store/dto/StyleDto.java
- src/main/java/com/kkosoonnae/store/exception/CustomException.java
- src/main/java/com/kkosoonnae/store/exception/ErrorCode.java
- src/main/java/com/kkosoonnae/store/service/StoreService.java
- src/main/java/com/kkosoonnae/store/service/StoreServiceImpl.java
> [feature:Add detailStore]

- src/main/java/com/kkosoonnae/jpa/entity/Review.java
- src/main/java/com/kkosoonnae/jpa/entity/Store.java
- src/main/java/com/kkosoonnae/jpa/entity/StoreImg.java
- src/main/java/com/kkosoonnae/jpa/projection/StoreListViewProjection.java
- src/main/java/com/kkosoonnae/jpa/repository/ReviewRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreImgRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreRepository.java
- src/main/java/com/kkosoonnae/store/dto/StoreListViewResponseDto.java
- src/main/java/com/kkosoonnae/store/exception/ErrorCode.java
- src/main/java/com/kkosoonnae/store/service/StoreServiceImpl.java
[feature]매장전체조회 : 평균별점구하기, 별점평균조회로직 생성
> [feature:Add avereage Scope]

- src/main/generated/com/kkosoonnae/jpa/entity/QLikeStore.java
- src/main/generated/com/kkosoonnae/jpa/entity/QReview.java
- src/main/generated/com/kkosoonnae/jpa/entity/QStore.java
- src/main/generated/com/kkosoonnae/jpa/entity/QStoreImg.java
- src/main/java/com/kkosoonnae/jpa/entity/LikeStore.java
- src/main/java/com/kkosoonnae/jpa/repository/LikeStoreRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StyleRepository.java
- src/main/java/com/kkosoonnae/store/controller/StoreController.java
- src/main/java/com/kkosoonnae/store/dto/LikeStoreDto.java
- src/main/java/com/kkosoonnae/store/exception/ErrorCode.java
- src/main/java/com/kkosoonnae/store/service/StoreService.java
- src/main/java/com/kkosoonnae/store/service/StoreServiceImpl.java
[feature]: 관심매장등록  , 관심매장삭제 구현 추가
> [feature:Add Like Store,Like deleteStore]

- src/main/java/com/kkosoonnae/jpa/entity/Notice.java
- src/main/java/com/kkosoonnae/jpa/repository/NoticeRepository.java
- src/main/java/com/kkosoonnae/notice/controller/NoticeController.java
- src/main/java/com/kkosoonnae/notice/dto/NoticeDto.java
- src/main/java/com/kkosoonnae/notice/service/NoticeService.java
- src/main/java/com/kkosoonnae/store/controller/StoreController.java
> [feature] 공지사항 조회 전체로 수정

- src/main/java/com/kkosoonnae/jpa/projection/StoreListViewProjection.java
- src/main/java/com/kkosoonnae/jpa/repository/LikeStoreRepository.java
- src/main/java/com/kkosoonnae/store/controller/StoreController.java
- src/main/java/com/kkosoonnae/store/dto/StoreDetailWithImageResponseDto.java
- src/main/java/com/kkosoonnae/store/dto/StoreListViewResponseDto.java
- src/main/java/com/kkosoonnae/store/exception/ErrorCode.java
- src/main/java/com/kkosoonnae/store/service/StoreService.java
- src/main/java/com/kkosoonnae/store/service/StoreServiceImpl.java
> [feature:관심매장 토탈수 조회 구현]

- src/main/java/com/kkosoonnae/batch/BatchConfiguration.java
배치를 이용해 data.csv에서 매장이름, 전화번호, 위치를 가져와서 저장
> feature:csv파일 읽어서 데이터 베이스에 저장하는 기능

- src/main/java/com/kkosoonnae/jpa/entity/Store.java
- src/main/java/com/kkosoonnae/jpa/entity/StoreImg.java
- src/main/java/com/kkosoonnae/store/dto/InputStoreInformation.java
- src/main/java/com/kkosoonnae/store/dto/StoreDto.java
- src/main/java/com/kkosoonnae/store/service/StoreServiceImpl.java
매장 등록시 매장이미지도 같이 등록 할 수 있도록 수정
> [fix]: 메장 등록할때 매장 이미지도 추가 할 수 있도록 구현

- src/main/java/com/kkosoonnae/jpa/repository/StoreRepository.java
- src/main/java/com/kkosoonnae/search/controller/SearchController.java
- src/main/java/com/kkosoonnae/store/controller/StoreController.java
> [hotfix:컨트롤러 임시예외처리]

- src/main/java/com/kkosoonnae/store/controller/StoreController.java
> [fix] operation 추가

- src/main/java/com/kkosoonnae/jpa/repository/StoreRepository.java
- src/main/java/com/kkosoonnae/search/controller/SearchController.java
- src/main/java/com/kkosoonnae/search/service/SearchService.java
- src/main/resources/application.yml
> [style:매장전체검색 키워드 변경]

- build.gradle
- src/main/generated/com/kkosoonnae/jpa/entity/QStore.java
- src/main/java/com/kkosoonnae/jpa/entity/Store.java
- src/main/java/com/kkosoonnae/jpa/enu/StyleType.java
- src/main/java/com/kkosoonnae/jpa/repository/ReviewRepository.java
- src/main/java/com/kkosoonnae/review/ReviewService.java
- src/main/java/com/kkosoonnae/store/controller/StoreController.java
- src/main/java/com/kkosoonnae/store/dto/ReviewDto.java
- src/main/java/com/kkosoonnae/store/dto/StoreDto.java
- src/main/java/com/kkosoonnae/store/service/StoreService.java
- src/main/resources/application.yml
매장정보 중에서 평점은 리뷰 별점 평균으로 나타내고 댓글은 가장 마지막에 남긴 댓글 보여주게 수정
> [fix]: 내 주변 매장 정보 평점, 댓글 기능

- src/main/java/com/kkosoonnae/store/controller/StoreController.java
- src/main/java/com/kkosoonnae/store/service/StoreService.java
[style:로그인 인증정보로 관심매장 추가, 삭제 로직변경]
> [style:로그인 인증정보로 관심매장 추가, 삭제 로직변경]

- build.gradle
- logs/server.log
redis 때문에 세큐리티랑 충돌이 일어나 redis 삭제
> [fix] : redis 충돌 문제 해결

- logs/server.log
- src/main/java/com/kkosoonnae/jpa/entity/Store.java
- src/main/java/com/kkosoonnae/jpa/entity/StoreImg.java
- src/main/java/com/kkosoonnae/jpa/entity/Style.java
- src/main/java/com/kkosoonnae/jpa/enu/StyleType.java
- src/main/java/com/kkosoonnae/jpa/repository/CustomerQueryRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreImgRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StyleRepository.java
- src/main/java/com/kkosoonnae/mypage/controller/MyPageController.java
- src/main/java/com/kkosoonnae/mypage/service/MyPageService.java
- src/main/java/com/kkosoonnae/store/controller/StoreController.java
- src/main/java/com/kkosoonnae/store/dto/StoreImageDTO.java
- src/main/java/com/kkosoonnae/store/exception/ErrorCode.java
- src/main/java/com/kkosoonnae/store/service/StoreService.java
- src/main/java/com/kkosoonnae/style/controller/StyleController.java
- src/main/java/com/kkosoonnae/style/dto/StyleDTO.java
- src/main/java/com/kkosoonnae/style/service/StyleService.java
유진님의 요청으로 스타일 이미지 사이즈 때문에 스타일 이미지 바꾸는 코드 추가, 매장 이미지 추가 하는 코드 추가
> [fearure] : 매장 이미지 바꾸는 코드 추가

- logs/server.log
- src/main/java/com/kkosoonnae/jpa/entity/CustomerBas.java
- src/main/java/com/kkosoonnae/jpa/projection/MainStoresListviewProjection.java
- src/main/java/com/kkosoonnae/jpa/projection/StoreReviewsViewProjection.java
- src/main/java/com/kkosoonnae/jpa/repository/LikeStoreRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreRepository.java
- src/main/java/com/kkosoonnae/mypage/controller/MyPageController.java
- src/main/java/com/kkosoonnae/mypage/service/MyPageService.java
- src/main/java/com/kkosoonnae/search/controller/SearchController.java
- src/main/java/com/kkosoonnae/search/dto/MainStoreListViewResponseDto.java
- src/main/java/com/kkosoonnae/search/service/SearchService.java
- src/main/java/com/kkosoonnae/store/controller/StoreController.java
- src/main/java/com/kkosoonnae/store/dto/StoreReviewsResponseDto.java
- src/main/java/com/kkosoonnae/store/service/StoreService.java
> [feature:매장리스트 조회구현 ]

- log/wrsungRestApi.log
- logs/server.log
- src/main/java/com/kkosoonnae/jpa/projection/StoreReviewsViewProjection.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreRepository.java
- src/main/java/com/kkosoonnae/store/dto/StoreReviewsResponseDto.java
- src/main/java/com/kkosoonnae/store/service/StoreService.java
> [style:평균별점 쿼리문에서 직접계산으로 변경]

- src/main/java/com/kkosoonnae/jpa/entity/StoreImg.java
- src/main/java/com/kkosoonnae/jpa/projection/StoreDetailViewProjection.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreImgRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreRepository.java
- src/main/java/com/kkosoonnae/store/dto/StoreDetailWithImageResponseDto.java
- src/main/java/com/kkosoonnae/store/dto/StoreImageDTO.java
- src/main/java/com/kkosoonnae/store/service/StoreService.java
매장 상세페이지에서 이미지가 2장이면 에러뜨는 현상 수정
> [fix] : 매장 상세페이지 수정

- src/main/java/com/kkosoonnae/jpa/projection/MainStoresListviewProjection.java
- src/main/java/com/kkosoonnae/jpa/projection/StoreDetailViewProjection.java
- src/main/java/com/kkosoonnae/jpa/projection/StoreListViewProjection.java
- src/main/java/com/kkosoonnae/jpa/projection/StoreReviewsViewProjection.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreImgRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreRepository.java
- src/main/java/com/kkosoonnae/search/dto/MainStoreListViewResponseDto.java
- src/main/java/com/kkosoonnae/search/dto/StoreListViewResponseDto.java
- src/main/java/com/kkosoonnae/search/service/SearchService.java
- src/main/java/com/kkosoonnae/store/service/StoreService.java
[style:전체검색키워드 매장이미지 리스트조회로 변경]
> [style:전체검색키워드 매장이미지 리스트조회로 변경]

- src/main/java/com/kkosoonnae/jpa/projection/MainStoresListviewProjection.java
- src/main/java/com/kkosoonnae/jpa/projection/StoreListViewProjection.java
- src/main/java/com/kkosoonnae/jpa/projection/StoreReviewsViewProjection.java
- src/main/java/com/kkosoonnae/jpa/repository/ReviewRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreImgRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreRepository.java
- src/main/java/com/kkosoonnae/search/dto/MainStoreListViewResponseDto.java
- src/main/java/com/kkosoonnae/search/dto/StoreListViewResponseDto.java
- src/main/java/com/kkosoonnae/search/service/SearchService.java
- src/main/java/com/kkosoonnae/store/controller/StoreController.java
- src/main/java/com/kkosoonnae/store/dto/StoreImgDto.java
- src/main/java/com/kkosoonnae/store/dto/StoreReviewsResponseDto.java
- src/main/java/com/kkosoonnae/store/exception/ErrorCode.java
- src/main/java/com/kkosoonnae/store/service/StoreService.java
[fix:매장이미지,매장평균별점 중복으로 불러와지는문제 수정]
> [fix:매장이미지,매장평균별점 중복으로 불러와지는문제 수정]

- src/main/java/com/kkosoonnae/jpa/projection/MainStoresListviewProjection.java
- src/main/java/com/kkosoonnae/jpa/projection/StoreDetailViewProjection.java
- src/main/java/com/kkosoonnae/jpa/projection/StoreReviewsViewProjection.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreRepository.java
- src/main/java/com/kkosoonnae/search/dto/MainStoreListViewResponseDto.java
- src/main/java/com/kkosoonnae/store/dto/StoreReviewsResponseDto.java
- src/main/java/com/kkosoonnae/store/service/StoreService.java
[style:강남구매장리스트 관심수추가 , 리뷰조회 리뷰날짜조회 추가]
> [style:강남구매장리스트 관심수추가 , 리뷰조회 리뷰날짜조회 추가]

- src/main/java/com/kkosoonnae/jpa/projection/MainStoresListviewProjection.java
- src/main/java/com/kkosoonnae/jpa/projection/StoreReviewsViewProjection.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreRepository.java
- src/main/java/com/kkosoonnae/review/service/ReviewService.java
- src/main/java/com/kkosoonnae/search/service/SearchService.java
- src/main/java/com/kkosoonnae/store/service/StoreService.java
> [style:매장평균별점 소수점보이게 다시변경]

- src/main/java/com/kkosoonnae/customer/controller/CustomerController.java
- src/main/java/com/kkosoonnae/customer/service/CustomerService.java
- src/main/java/com/kkosoonnae/mypage/controller/MyPageController.java
- src/main/java/com/kkosoonnae/mypage/service/MyPageService.java
- src/main/java/com/kkosoonnae/pet/controller/PetController.java
- src/main/java/com/kkosoonnae/pet/service/PetService.java
- src/main/java/com/kkosoonnae/point/controller/PointController.java
- src/main/java/com/kkosoonnae/point/service/PointService.java
- src/main/java/com/kkosoonnae/qna/controller/QnaController.java
- src/main/java/com/kkosoonnae/qna/service/QnaService.java
서비스에 있던 로그인 정보 받아오는걸 controller로 이동하였습니다.
> [fix] : service 단에 있는 시큐리티 로그인 정보 controller 이동

- src/main/java/com/kkosoonnae/jpa/repository/CustomerQueryRepository.java
- src/main/java/com/kkosoonnae/mypage/dto/AvailDto.java
> [fix] : 예약 매장 이미지 오류

- src/main/java/com/kkosoonnae/customer/controller/CustomerController.java
- src/main/java/com/kkosoonnae/mypage/controller/MyPageController.java
- src/main/java/com/kkosoonnae/notice/controller/NoticeController.java
- src/main/java/com/kkosoonnae/pet/controller/PetController.java
- src/main/java/com/kkosoonnae/point/controller/PointController.java
- src/main/java/com/kkosoonnae/qna/controller/QnaController.java
- src/main/java/com/kkosoonnae/reservation/controller/ReservationController.java
- src/main/java/com/kkosoonnae/search/controller/SearchController.java
- src/main/java/com/kkosoonnae/store/controller/StoreController.java
- src/main/java/com/kkosoonnae/style/controller/StyleController.java
> [fix] : 엔드 포인트 -> api 로 수정

- src/main/java/com/kkosoonnae/common/advice/ErrorResponse.java
- src/main/java/com/kkosoonnae/common/advice/ExceptionControllerAdvice.java
- src/main/java/com/kkosoonnae/common/exception/CustomException.java
- src/main/java/com/kkosoonnae/common/exception/DuplicateStoreNameException.java
- src/main/java/com/kkosoonnae/common/exception/ErrorCode.java
- src/main/java/com/kkosoonnae/jpa/entity/Store.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreRepository.java
- src/main/java/com/kkosoonnae/president/mystore/controller/MyStoreController.java
- src/main/java/com/kkosoonnae/president/mystore/dto/AdminStoreImgRequestDto.java
- src/main/java/com/kkosoonnae/president/mystore/dto/AdminStoreRequestDto.java
- src/main/java/com/kkosoonnae/president/mystore/service/MyStoreService.java
- src/main/java/com/kkosoonnae/user/search/controller/SearchController.java
- src/main/java/com/kkosoonnae/user/store/controller/StoreController.java
[style:컨트롤러단  엔드포인트 변경 , Tag설명 추가]
> [style:컨트롤러단  엔드포인트 변경 , Tag설명 추가]

- src/main/java/com/kkosoonnae/user/reservation/service/ReservationService.java
> [fix] 예약시 분기처리 추가.

- src/main/java/com/kkosoonnae/common/advice/ErrorResponse.java
- src/main/java/com/kkosoonnae/common/advice/ExceptionControllerAdvice.java
- src/main/java/com/kkosoonnae/common/exception/CustomException.java
- src/main/java/com/kkosoonnae/common/exception/DuplicateStoreNameException.java
- src/main/java/com/kkosoonnae/common/exception/ErrorCode.java
- src/main/java/com/kkosoonnae/president/mystore/controller/MyStoreController.java
- src/main/java/com/kkosoonnae/president/mystore/service/MyStoreService.java
- src/main/java/com/kkosoonnae/user/search/controller/SearchController.java
- src/main/java/com/kkosoonnae/user/search/service/SearchService.java
- src/main/java/com/kkosoonnae/user/store/controller/StoreController.java
- src/main/java/com/kkosoonnae/user/store/service/StoreService.java
> [refactor:예외처리 리팩토링]

- src/main/java/com/kkosoonnae/config/auth/PrincipalDetailService.java
- src/main/java/com/kkosoonnae/config/jwt/JwtAuthenticationFilter.java
- src/main/java/com/kkosoonnae/config/jwt/JwtFilter.java
- src/main/java/com/kkosoonnae/config/jwt/JwtTokenProvider.java
- src/main/java/com/kkosoonnae/config/jwt/TokenProvider.java
- src/main/java/com/kkosoonnae/config/security/SecurityConfig.java
- src/main/java/com/kkosoonnae/jpa/entity/RoleType.java
- src/main/java/com/kkosoonnae/president/info/controller/InfoController.java
- src/main/java/com/kkosoonnae/president/info/service/InfoService.java
- src/main/java/com/kkosoonnae/user/customer/controller/CustomerController.java
- src/main/java/com/kkosoonnae/user/customer/dto/TokenResponseDto.java
- src/main/java/com/kkosoonnae/user/customer/service/CustomerService.java
임시 jwt 생성입니다. 로그인 부분이 안되는 이슈로 인해 수정 예정입니다.
> [fix] jwt 임시 커밋

- build.gradle
- src/main/java/com/kkosoonnae/common/exception/ErrorCode.java
- src/main/java/com/kkosoonnae/config/RedisConfig.java
- src/main/java/com/kkosoonnae/jpa/entity/Store.java
- src/main/java/com/kkosoonnae/jpa/entity/StoreImg.java
- src/main/java/com/kkosoonnae/jpa/repository/RedisLikeStoreRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/RedisLockRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/RedisScopeRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreImgRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreRepository.java
- src/main/java/com/kkosoonnae/president/mystore/controller/MyStoreController.java
- src/main/java/com/kkosoonnae/president/mystore/dto/AdminStoreImgRequestDto.java
- src/main/java/com/kkosoonnae/president/mystore/dto/AdminStoreRequestDto.java
- src/main/java/com/kkosoonnae/president/mystore/service/MyStoreService.java
- src/main/resources/application.yml
[feature:어드민 매장등록,매장이미지등록,수정,삭제 api 구현]
> [feature:어드민 매장등록,매장이미지등록,수정,삭제 api 구현]

- src/main/generated/com/kkosoonnae/president/reservationmanage/service/ReservationMapperImpl.java
- src/main/java/com/kkosoonnae/config/RedisConfig.java
- src/main/java/com/kkosoonnae/jpa/projection/MainStoresListviewProjection.java
- src/main/java/com/kkosoonnae/jpa/repository/RedisLikeStoreRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/RedisScopeRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreQueryRepository.java
- src/main/java/com/kkosoonnae/president/mystore/dto/AdminStoreRequestDto.java
- src/main/java/com/kkosoonnae/president/mystore/service/MyStoreService.java
- src/main/java/com/kkosoonnae/president/reservationmanage/service/ReservationMapper.java
- src/main/java/com/kkosoonnae/user/review/service/ReviewService.java
- src/main/java/com/kkosoonnae/user/search/dto/MainStoreListViewResponseDto.java
- src/main/java/com/kkosoonnae/user/search/service/SearchService.java
- src/main/java/com/kkosoonnae/user/store/service/StoreService.java
- src/main/resources/application.yml
> [feature:redis 설정]

- src/main/generated/com/kkosoonnae/president/reservationmanage/service/ReservationMapperImpl.java
- src/main/java/com/kkosoonnae/config/RedisConfig.java
- src/main/java/com/kkosoonnae/jpa/projection/MainStoresListviewProjection.java
- src/main/java/com/kkosoonnae/jpa/repository/RedisLikeStoreRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/RedisScopeRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreQueryRepository.java
- src/main/java/com/kkosoonnae/president/mystore/controller/MyStoreController.java
- src/main/java/com/kkosoonnae/president/mystore/dto/AdminStoreRequestDto.java
- src/main/java/com/kkosoonnae/president/mystore/dto/AdminStoreResponseDto.java
- src/main/java/com/kkosoonnae/president/mystore/service/MyStoreService.java
- src/main/java/com/kkosoonnae/user/search/dto/MainStoreListViewResponseDto.java
- src/main/java/com/kkosoonnae/user/search/dto/StoreListViewResponseDto.java
- src/main/java/com/kkosoonnae/user/search/service/SearchService.java
- src/main/java/com/kkosoonnae/user/store/controller/StoreController.java
- src/main/resources/application.yml
[fix: 어드민 매장생성 업데이트 ,리스폰스 디티오로 교체]
> [fix: 어드민 매장생성 업데이트 ,리스폰스 디티오로 교체]

- src/main/generated/com/kkosoonnae/jpa/entity/QTerm.java
- src/main/generated/com/kkosoonnae/jpa/entity/QTermsAgreeTxn.java
- src/main/java/com/kkosoonnae/jpa/entity/RoleType.java
- src/main/java/com/kkosoonnae/president/info/service/InfoService.java
- src/main/java/com/kkosoonnae/user/customer/controller/CustomerController.java
- src/main/java/com/kkosoonnae/user/customer/dto/SignUpDto.java
- src/main/java/com/kkosoonnae/user/customer/dto/TermDto.java
- src/main/java/com/kkosoonnae/user/customer/service/CustomerService.java
> [feature] 회원가입 시 약관 동의 내역 저장

- build.gradle
- src/main/generated/com/kkosoonnae/user/store/dto/QStoreReviewsResponseDto.java
- src/main/java/com/kkosoonnae/config/QueryDSLConfig.java
- src/main/java/com/kkosoonnae/jpa/projection/MainStoresListviewProjection.java
- src/main/java/com/kkosoonnae/jpa/projection/StoreListViewProjection.java
- src/main/java/com/kkosoonnae/jpa/projection/StoreReviewsViewProjection.java
- src/main/java/com/kkosoonnae/jpa/repository/RedisLikeStoreRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/RedisScopeRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreQueryRepository.java
- src/main/java/com/kkosoonnae/user/review/service/ReviewService.java
- src/main/java/com/kkosoonnae/user/search/controller/SearchController.java
- src/main/java/com/kkosoonnae/user/search/dto/MainStoreListViewResponseDto.java
- src/main/java/com/kkosoonnae/user/search/dto/StoreListViewResponseDto.java
- src/main/java/com/kkosoonnae/user/search/service/SearchService.java
- src/main/java/com/kkosoonnae/user/store/dto/StoreDetailWithImageResponseDto.java
- src/main/java/com/kkosoonnae/user/store/dto/StoreImageDTO.java
- src/main/java/com/kkosoonnae/user/store/dto/StoreImgDto.java
- src/main/java/com/kkosoonnae/user/store/dto/StoreReviewsResponseDto.java
- src/main/java/com/kkosoonnae/user/store/service/StoreService.java
- src/main/resources/application.yml
> [refactor:JPA쿼리 쿼리dsl로 변경]

- src/main/generated/com/kkosoonnae/user/store/dto/QStoreDetailWithImageResponseDto.java
- src/main/java/com/kkosoonnae/jpa/repository/RedisLikeStoreRepository.java
- src/main/java/com/kkosoonnae/jpa/repository/StoreQueryRepository.java
- src/main/java/com/kkosoonnae/user/store/dto/StoreDetailWithImageResponseDto.java
- src/main/java/com/kkosoonnae/user/store/service/StoreService.java
> [fix:레디스 관심수 전체삭제되는 오류수정]
